// lib/main.dart
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
// Add this import
import 'app_routes.dart';
import 'package:talkwise/pages/theme_provider.dart';
import 'package:talkwise/pages/pronunciation_backend.dart';
import 'package:talkwise/pages/lessons_backend.dart'; // Add this import
import 'package:talkwise/pages/progress_backend.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (context) => ThemeProvider()),
        ChangeNotifierProvider(create: (context) => PronunciationBackend()),
        ChangeNotifierProvider(
          create: (context) => LessonsBackend(),
        ), // Add this line
        ChangeNotifierProvider(create: (_) => ProgressBackend()),
      ],
      child: Builder(
        builder: (context) {
          final themeProvider = Provider.of<ThemeProvider>(context);

          return MaterialApp(
            title: 'TalkWise',
            theme: ThemeData(
              primarySwatch: Colors.blue,
              brightness: Brightness.light,
            ),
            darkTheme: ThemeData(
              primarySwatch: Colors.blue,
              brightness: Brightness.dark,
            ),
            themeMode: themeProvider.isDarkMode
                ? ThemeMode.dark
                : ThemeMode.light,
            initialRoute: AppRoutes.login,
            routes: AppRoutes.routes,
          );
        },
      ),
    );
  }
}
